### ISSUE TITLE
Should be able to return the rest of the batch when the stream end

### ISSUE THREAD

**Issue by bobylito** [segmentio/batch-stream#7]
When a stream contains a number of items that is not a strict multiply of the batch size, it results in some items that are not passed to then next stream process.

**Comment by eric-radiant** [comment]
That would be great to have fixed.

**Comment by roccomuso** [comment]
Totally agree. I published a package that solves this issue: [batched-stream](https://github.com/roccomuso/batched-stream)

**Comment by richardscarrott** [comment]
I think it already does https://github.com/segmentio/batch-stream/blob/master/lib/index.js#L38?

**Comment by bobylito** [comment]
> I think it already does https://github.com/segmentio/batch-stream/blob/master/lib/index.js#L38?

When I initially reported the issue, it was not working like I expected as far as I can recall. The file was last modified before I opened the issue. So either it is not fixed, or I reported something incorrectly 😅 

I think I should provide a test case for that :)

**Comment by bobylito** [comment]
> I think I should provide a test case for that :)

On the other hand, is it even worth it? There is a PR hanging sincw 2014 😅
